Update Prism_PrismTrello_Functions.py
- lines 49 to 78:
replaced the err_decorator with err_catcher from PrismUtils (took Prism's Shotgun plugin as reference).

- line 211:
onStateCreated is returning a TypeError. Commented it out for now.
#
/Plugins/Custom/PrismTrello/Scripts/Prism_PrismTrello_Functions.py", line 65, in func_wrapper
    return func(*args, **kwargs)
TypeError: onStateCreated() takes exactly 2 arguments (4 given)
#

- line 243:
If an Asset is created from Project Browser it a card is not created on Trello (only the other way around). Added this line hoping to fix it but no luck.

- line 324:
"outputName" is now "outputpath"

- line 325 to 328:
localProjectPath doesn't exist if not enabled on project settings. Commented out for now.
#
Plugins/Custom/PrismTrello/Scripts/Prism_PrismTrello_Functions.py", line 325, in publish_task_to_trello
    if publish_file.startswith(os.path.normpath(self.core.localProjectPath)):
AttributeError: PrismCore instance has no attribute 'localProjectPath'
#

- line 331:
"startframe" and "endframe" are lower case now.

- lines 367, 373, 379:
.ini was returning a TypeError. Changing it to .yml seems to have fixed it.
#
Plugins/Custom/PrismTrello/Scripts/Prism_PrismTrello_Functions.py", line 416, in get_publish_data
    config_items = dict(self.core.getConfig(configPath=vinfo_path, cat="information"))
TypeError: 'NoneType' object is not iterable
#

- line 415:
Couldn't found "getItems" parameter in "getConfig". Works without it.
#
Plugins/Custom/PrismTrello/Scripts/Prism_PrismTrello_Functions.py", line 415, in get_publish_data
    config_items = dict(self.core.getConfig(configPath=vinfo_path, getItems=True, cat="information"))
  File "/Applications/Prism/Scripts/PrismUtils/Decorators.py", line 79, in func_wrapper
    "".join(traceback.format_stack()),

Traceback (most recent call last):
  File "/Applications/Prism/Scripts/PrismUtils/Decorators.py", line 57, in func_wrapper
    return func(*args, **kwargs)
TypeError: getConfig() got an unexpected keyword argument 'getItems'
#

- lines 418 and 419:
"Version" and "Creation date" are capitalized.

- line 421:
Entity's versioninfo.yml file have "Dependencies" as an empty list but Asset's versioninfo.yml file doesn't have it.

==========

So far, sync is working on both ways (except when asset is created on Prism, see line 243) and cards are registering updates when Asset is exported. Need to test with other states (Playblast, Render, etc).
By the moment, testing it on MacOSX, Maya2018, Trello non-commercial.