Update trelloprism.py
Line 293: I believe it had a small typo. Changing it to "getAssetPath" passed without AttributeError:
#
PrismTrello/Scripts/trelloprism.py", line 294, in sync_from_prism
    asset_paths = self.core.getAssetPath()
AttributeError: PrismCore instance has no attribute 'getAssetPaths'
#

Other changes and print statements were added trying to solve "HTTPError" when clicking over "Sync Prism -> Trello" button:
#
PrismTrello/Scripts/trelloprism.py", line 149, in send
    raise requests.HTTPError(content)
HTTPError: invalid value for name
#